<!-- on inclut le header de la page avec la fonction "include" -->
<?php include('C:\Users\Panda\Desktop\Projet_Final_PHP\view\templates\header.phtml') ?>

<section>
    <h2 class="display-4">Modifier l'élève</h2>
    <form class="update" action="." method="POST">
        <div class="form-group">
            <input type="hidden" name="action" value="update">
            <input type="hidden" name="id" value="<?= $eleve['ID'] ?>">
            <label for="prenom">Prénom de l'élève :</label>
            <input class="form-control" type="text" id="prenom" name="prenom" value="<?= $eleve['prenom'] ?>" required>
            <label for="nom">Nom de l'élève :</label>
            <input class="form-control" type="text" id="nom" name="nom" value="<?= $eleve['nom'] ?>" required>
            <label for="age">Âge de l'élève :</label>
            <input class="form-control" type="text" id="age" name="age" value="<?= $eleve['age'] ?>" required>
            <label for="email">Email de l'élève :</label>
            <input class="form-control" type="text" id="email" name="email" value="<?= $eleve['email'] ?>" required>
            <button class="btn btn-primary">Mettre à jour</button>
        </div>
    </form>
</section>

<!-- On inclut le fichier "status" -->
<?php include('C:\Users\Panda\Desktop\Projet_Final_PHP\view\eleves\status.php') ?>
<p><a href=".">Retourner à la liste des élèves.</a></p>
<?php include('C:\Users\Panda\Desktop\Projet_Final_PHP\view\templates\footer.phtml') ?>