<?php include('C:\Users\Panda\Desktop\Php_Projet_Final_Caroen-main\Php_Projet_Final_Caroen-main\Projet_Final_PHP\view\templates\header.phtml') ?>
<!-- On inclut le header -->

<h1 class="display-1">Erreur</h1>
<br>
<!-- On affiche un messgae d'erreur personnalisé qui a été passé à cette page -->
<br>
<p><a href=".">Retourner au formulaire de création</a></p>
<!-- On affiche un lien pour retourner au formulaire de création -->

<?php include('C:\Users\Panda\Desktop\Projet_Final_PHP\view\templates\footer.phtml') ?>
<!-- On inclut le footer -->